### ISSUE TITLE
  After a fresh install the pdfjs-dist shows the problem

### ISSUE THREAD

**Issue by MajedSardar64** [mablay/pdf-export-images#2]
file:///C:/Users/SARDAR/Desktop/IMG_text_OCR/node_modules/pdfjs-dist/build/pdf.mjs:5300
  var packageCapability = Promise.withResolvers();
                                  ^

TypeError: Promise.withResolvers is not a function

![image](https://github.com/mablay/pdf-export-images/assets/65985061/c0b959be-39f0-4d63-913b-b09f7f3f083c)

**Comment by mablay** [comment]
Hey there, this looks like a windows issue with the sub-dependency "[pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist)". I won't be able to reproduce / test windows issues and recommend checking this dependency for similar issues.

As a side note, it's always a good idea to add your NodeJS version, OS version etc. for context.

PRs are welcome

**Comment by MajedSardar64** [comment]
A previous application showing similar paths after an install may have problems with libraries that were previously installed.

**Comment by dev3py** [comment]
async function asPDF({ fullFilePath = "", filename = "" }) {

  outputdir = '/app/collector/processSingleFile/convert/images'
  try {
    const pdfExportImagesModule = await import('pdf-export-images');
    const exportImages = pdfExportImagesModule.exportImages;

    const images = await exportImages(fullFilePath, outputdir);
    console.log('Exported images========================', images.length, 'images');
  } catch (error) {
    console.error(error);
  }
  }
  
  
  TypeError: Promise.withResolvers is not a function
    at file:///app/collector/node_modules/pdfjs-dist/build/pdf.mjs:5300:35
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:432:15)
    at async asPDF (/app/collector/processSingleFile/convert/asPDF.js:18:35)
    at async processSingleFile (/app/collector/processSingleFile/index.js:54:10)
    at async /app/collector/index.js:37:9

Error processing images [Error: ENOENT: no such file or directory, scandir '/app/collector/processSingleFile/convert/images'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/app/collector/processSingleFile/convert/images'
}

I am getting the same error i am using this build in dockerfile. With os running in ubuntu latest version. And the nodejs version is 18.12.1

**Comment by MajedSardar64** [comment]
pdfjs-dist Update to latest Version 4.6.82

**Comment by mablay** [comment]
@MajedSardar64 if this sentence suggests upgrading the dependency, feel free to create a PR.

**Comment by mablay** [comment]
closing due to inactivity
